### ISSUE TITLE
[1.19.2 Forge] Nether Render

### ISSUE THREAD

**Issue by HalcyonSeas73** [Pepperoni-Jabroni/MapAtlases#61]
Map Atlas version: 3.0.1
Forge version: 43.1.1
Minecraft version: 1.19.2

Not sure if this is the appropriate repo to report Forge bugs on.
When in the Nether, the map renders as shown, with the player icon slowly spinning in circles. Is this intended behaviour? Is mapping in the Nether not yet supported?

Edit: ~~Furthermore, after going back through the portal, rather than putting me back where I entered, I re-enter Overworld at a different location, just west of where I originally entered the Nether. **This continues even after I remove Map Atlases from the world.**~~ _this was caused by a different mod_

![Untitled](https://user-images.githubusercontent.com/84727791/186502236-08bae5cb-c702-41e0-8939-aa355927dff4.png)

**Comment by Pepperoni-Jabroni** [comment]
Thanks for reporting! This is the repo for the Fabric version of the game, but it appears Lily hasn't linked the Forge repo on the Curseforge page. As a result, I think its fine to report your Issues here.

Regarding your question, yes - this is intended. This is how vanilla Maps behave in the Nether! And Map Atlases doesn't make any changes to how Maps function in the Nether. So I'm going close this out since it's not an Issue. Thanks for reporting!
